fixing wrong comment out

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -18,29 +18,29 @@ jobs:
       - name: Detect Changes
         uses: './.github/actions/diffs'
         id: diff
-
-  spelling:
-    name: Lint documentation
-    needs: diff
-    if: needs.diff.outputs.isDoc == 'true'
-    runs-on: [ubuntu-latest]
-
-    steps:
-      - uses: actions/checkout@v3 # pin@v3
-      - name: Spell Check Docs
-        uses: crate-ci/typos@v1.16.11
-        with:
-          files: ./docs/content ./*.mdx
-
+  
   # TODO: @ronny-mysten to enable this once we are ready
-  # old-doc-folder-notice:
-  #   name: Old doc folder notice
+  # spelling:
+  #   name: Lint documentation
   #   needs: diff
-  #   if: needs.diff.outputs.isOldDoc == 'true'
+  #   if: needs.diff.outputs.isDoc == 'true'
   #   runs-on: [ubuntu-latest]
 
   #   steps:
-  #     - name: Output error
-  #       run: |
-  #         echo "::error::Sui documentation has moved from doc/* to docs/content/* folder. (*.md files are now *.mdx)"
-  #         exit 1
+  #     - uses: actions/checkout@v3 # pin@v3
+  #     - name: Spell Check Docs
+  #       uses: crate-ci/typos@v1.16.11
+  #       with:
+  #         files: ./docs/content ./*.mdx
+
+  old-doc-folder-notice:
+    name: Old doc folder notice
+    needs: diff
+    if: needs.diff.outputs.isOldDoc == 'true'
+    runs-on: [ubuntu-latest]
+
+    steps:
+      - name: Output error
+        run: |
+          echo "::error::Sui documentation has moved from doc/* to docs/content/* folder. (*.md files are now *.mdx)"
+          exit 1
