disabling spellcheck for now

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -32,14 +32,15 @@ jobs:
         with:
           files: ./docs/content ./*.mdx
 
-  old-doc-folder-notice:
-    name: Old doc folder notice
-    needs: diff
-    if: needs.diff.outputs.isOldDoc == 'true'
-    runs-on: [ubuntu-latest]
+  # TODO: @ronny-mysten to enable this once we are ready
+  # old-doc-folder-notice:
+  #   name: Old doc folder notice
+  #   needs: diff
+  #   if: needs.diff.outputs.isOldDoc == 'true'
+  #   runs-on: [ubuntu-latest]
 
-    steps:
-      - name: Output error
-        run: |
-          echo "::error::Sui documentation has moved from doc/* to docs/content/* folder. (*.md files are now *.mdx)"
-          exit 1
+  #   steps:
+  #     - name: Output error
+  #       run: |
+  #         echo "::error::Sui documentation has moved from doc/* to docs/content/* folder. (*.md files are now *.mdx)"
+  #         exit 1
