fixing again

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -46,8 +46,8 @@ jobs:
       - name: Clean up and validate tag name ${{ env.TAG_NAME }}
         shell: bash
         run: | 
+          [[ ${{ env.TAG_NAME }} == "main" ]] && echo "tag cannot be equals to 'main'" && exit 1
           echo "sui_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
-          [[ ${sui_tag} == "main" ]] && echo "tag cannot be equals to 'main'" && exit 1
 
       - name: Configure AWS credentials
         if: ${{ env.TAG_NAME != 'main' }}
