removing aws cli

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -43,6 +43,12 @@ jobs:
       fail-fast: false
     runs-on: ${{ matrix.os }}
     steps:
+      - name: Clean up and validate tag name ${{ env.TAG_NAME }}
+        shell: bash
+        run: | 
+          echo "sui_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
+          [[ ${{ env.sui_tag }} == "main" ]] && echo "tag cannot be equals to 'main'" && exit 1
+
       - name: Configure AWS credentials
         if: ${{ env.TAG_NAME != 'main' }}
         uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # pin@v1
@@ -51,13 +57,8 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-west-2
 
-      - name: Clean up tag name ${{ env.TAG_NAME }}
-        shell: bash
-        run: | 
-          echo "sui_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
-
       - name: Set os/arch variables (Windows)
-        if: ${{ env.sui_tag != 'main' && matrix.os == 'windows-ghcloud' }}
+        if: ${{ matrix.os == 'windows-ghcloud' }}
         shell: bash
         run: |
           export arch=$(uname -m)
@@ -65,19 +66,13 @@ jobs:
           echo "os_type=${os_type}" >> $GITHUB_ENV
 
       - name: Set os/arch variables
-        if: ${{ env.sui_tag != 'main' && matrix.os != 'windows-ghcloud' }}
+        if: ${{ matrix.os != 'windows-ghcloud' }}
         shell: bash
         run: |
           export arch=$(uname -m)
           export system_os=$(echo ${{ matrix.os }} | cut -d- -f1)
           export os_type="${system_os}-${arch}"
           echo "os_type=${system_os}-${arch}" >> $GITHUB_ENV     
-        
-      - name: Checking out ${{ env.sui_tag }}
-        if: ${{ env.sui_tag != 'main' }}
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ env.sui_tag }}
 
       - name: Check if archives of binaries have already been built
         continue-on-error: true
@@ -93,22 +88,22 @@ jobs:
           aws s3 cp s3://sui-releases/releases/sui-${{ env.sui_tag }}-${os_type}.tgz ./target/release/sui-${{ env.sui_tag }}-${os_type}.tgz
 
       - name: Setup caching
-        if: ${{ env.sui_tag != 'main' && env.s3_archive_exist == '' }}
+        if: ${{ env.s3_archive_exist == '' }}
         uses: bmwill/rust-cache@v1 # Fork of 'Swatinem/rust-cache' which allows caching additional paths          
       
       - name: Install nexttest (Windows)
-        if: ${{ matrix.os == 'windows-ghcloud' && env.sui_tag != 'main' && env.s3_archive_exist == '' }}
+        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
         uses: taiki-e/install-action@nextest
 
       - name: Setup protoc (Windows)
-        if: ${{ matrix.os == 'windows-ghcloud' && env.sui_tag != 'main' && env.s3_archive_exist == '' }}
+        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
         uses: arduino/setup-protoc@v1
         # this avoids rate-limiting
         with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Install postgres (Windows)
-        if: ${{ matrix.os == 'windows-ghcloud' && env.sui_tag != 'main' && env.s3_archive_exist == '' }}
+        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
         shell: bash
         run: |
           choco install postgresql12 --force --params '/Password:root'
@@ -117,20 +112,22 @@ jobs:
           echo "PQ_LIB_DIR=C:\Program Files\PostgreSQL\12\lib" >> $GITHUB_ENV
           echo "PG_DATABASE_URL=postgres://postgres:root@localhost/" >> $GITHUB_ENV
           echo "PG_EXAMPLE_DATABASE_URL=postgres://postgres:root@localhost/diesel_example" >> $GITHUB_ENV
-          
-      - name: Install aws for ${{ matrix.os }}
-        if: ${{ matrix.os == 'macos-arm64-self-hosted' && env.sui_tag != 'main' && env.s3_archive_exist == '' }}
-        uses: chrislennon/action-aws-cli@v1.1
+
+      - name: Checking out ${{ env.sui_tag }}
+        if: ${{ env.s3_archive_exist == '' }}
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ env.sui_tag }}        
 
       - name: cargo build (release) for ${{ matrix.os }} platform
-        if: ${{ env.sui_tag != 'main' && env.s3_archive_exist == '' }}
+        if: ${{ env.s3_archive_exist == '' }}
         shell: bash
         run: |
           [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --release
           cd external-crates/move && cargo build -p move-analyzer --release
 
       - name: Rename binaries for ${{ matrix.os }}
-        if: ${{ env.sui_tag != 'main' && matrix.os != 'windows-ghcloud' && env.s3_archive_exist == '' }}
+        if: ${{ matrix.os != 'windows-ghcloud' && env.s3_archive_exist == '' }}
         shell: bash
         run: |
           [ -f ./target/release/sui ] && mv ./target/release/sui ./target/release/sui-${os_type}
@@ -144,7 +141,7 @@ jobs:
           [[ ${{ env.sui_tag }} == *"mainnet"* ]] && aws s3 cp ./target/release/sui-${{ env.sui_tag }}-${os_type}.tgz s3://sui-releases/releases/sui-${{ env.sui_tag }}-${os_type}.tgz || true
 
       - name: Rename binaries for Windows
-        if: ${{ env.sui_tag != 'main' && matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
+        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
         shell: bash
         run: |
           [ -f ./target/release/sui.exe ] && mv ./target/release/sui.exe ./target/release/sui-${os_type}.exe
@@ -159,7 +156,6 @@ jobs:
           [[ ${{ env.sui_tag }} == *"mainnet"* ]] && aws s3 cp ./target/release/sui-${{ env.sui_tag }}-${os_type}.tgz s3://sui-releases/releases/sui-${{ env.sui_tag }}-${os_type}.tgz || true
 
       - name: Upload release artifacts for ${{ matrix.os }} platform
-        if: ${{ env.sui_tag != 'main' }}
         uses: actions/upload-artifact@v3
         with:
           name: sui-binaries-${{ matrix.os }}
@@ -168,7 +164,6 @@ jobs:
             ./target/release/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz
 
       - name: Publish binaries for ${{ env.sui_tag }} release
-        if: ${{ env.sui_tag != 'main' }}
         uses: softprops/action-gh-release@v1
         with:
           tag_name: ${{ env.sui_tag }}
