fixing sui_tag cleaning

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -45,9 +45,10 @@ jobs:
     steps:
       - name: Clean up and validate tag name ${{ env.TAG_NAME }}
         shell: bash
-        run: | 
-          [[ "${{ env.TAG_NAME }}" == "main" ]] && echo "tag cannot be equals to 'main'" && exit 1
-          echo "sui_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
+        run: |
+          export sui_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)"
+          [[ "${sui_tag}" == "main" ]] && echo "tag cannot be equals to 'main'" && exit 1
+          echo "sui_tag=${sui_tag}" >> $GITHUB_ENV
 
       - name: Configure AWS credentials
         if: ${{ env.TAG_NAME != 'main' }}
