Check if tar ball for the same version was already built

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -94,28 +94,28 @@ jobs:
           export os_type="${system_os}-${arch}"
           echo "os_type=${system_os}-${arch}" >> $GITHUB_ENV     
 
-      - name: Check if archive have already been published
+      - name: Check if archive for this version has already been published
         continue-on-error: true
         shell: bash
         run: |
-          echo "s3_archive_exist=$(curl -Is https://sui-releases.s3.us-east-1.amazonaws.com/releases/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz | head -n 1 | grep '200 OK')" >> $GITHUB_ENV
+          echo "s3_existing_archive=$(aws s3 ls s3://sui-releases/releases/ --recursive | grep "${{ env.sui_version }}-${{ env.os_type }}.tgz" | head -n1 | awk '{print $3}' || echo '')" >> $GITHUB_ENV
 
       - name: Download archive, if it exists
-        if: ${{ env.s3_archive_exist != '' }}
+        if: ${{ env.s3_existing_archive != '' }}
         shell: bash
         run: |
           mkdir -p ${{ env.TMP_BUILD_DIR }}
-          aws s3 cp s3://sui-releases/releases/sui-${{ env.sui_tag }}-${os_type}.tgz ./tmp/sui-${{ env.sui_tag }}-${os_type}.tgz
-          tar -xf ./tmp/sui-${{ env.sui_tag }}-${os_type}.tgz -C ${{ env.TMP_BUILD_DIR }}     
+          aws s3 cp s3://sui-releases/${{ env.s3_existing_archive }} ./tmp/sui-${{ env.sui_tag }}-${os_type}.tgz
+          tar -xf ./tmp/sui-${{ env.sui_tag }}-${os_type}.tgz -C ${{ env.TMP_BUILD_DIR }}
 
       - name: Install nexttest (Windows)
-        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
+        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_existing_archive == '' }}
         uses: taiki-e/install-action@7bf3bbf3104a2e9a77906ccbdf6d4aa6a87b0210 # pin@2.52.5
         with:
           tool: cargo-hack
 
       - name: Install postgres (Windows)
-        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_archive_exist == '' }}
+        if: ${{ matrix.os == 'windows-ghcloud' && env.s3_existing_archive == '' }}
         shell: bash
         run: |
           choco install postgresql12 --force --params '/Password:root'
@@ -126,7 +126,7 @@ jobs:
           echo "PG_EXAMPLE_DATABASE_URL=postgres://postgres:root@localhost/diesel_example" >> $GITHUB_ENV
 
       - name: Install postgres (MacOS arm64)
-        if: ${{ matrix.os == 'macos-latest-xlarge' && env.s3_archive_exist == '' }}
+        if: ${{ matrix.os == 'macos-latest-xlarge' && env.s3_existing_archive == '' }}
         shell: bash
         env:
           PQ_LIB_DIR: "$(brew --prefix libpq)/lib"
@@ -137,13 +137,13 @@ jobs:
           brew install postgresql
 
       - name: Install postgres (Ubuntu arm64)
-        if: ${{ matrix.os == 'ubuntu-arm64' && env.s3_archive_exist == '' }}
+        if: ${{ matrix.os == 'ubuntu-arm64' && env.s3_existing_archive == '' }}
         shell: bash
         run: |
           sudo apt update && sudo apt install libpq-dev
 
       - name: Remove unused apps (MacOS arm64)
-        if: ${{ matrix.os == 'macos-latest-xlarge' && env.s3_archive_exist == '' }}
+        if: ${{ matrix.os == 'macos-latest-xlarge' && env.s3_existing_archive == '' }}
         continue-on-error: true
         shell: bash
         run: |
@@ -156,13 +156,13 @@ jobs:
           df -h /
 
       - name: Cargo build for ${{ matrix.os }} platform
-        if: ${{ env.s3_archive_exist == '' }}
+        if: ${{ env.s3_existing_archive == '' }}
         shell: bash
         run: |
           [ -f ~/.cargo/env ] && source ~/.cargo/env ; cargo build --release && cargo build --release --features tracing --bin sui && cargo build --profile=dev --bin sui --features tracing
 
       - name: Rename binaries for ${{ matrix.os }}
-        if: ${{ env.s3_archive_exist == '' }}
+        if: ${{ env.s3_existing_archive == '' }}
         shell: bash
         run: |
           mkdir -p ${{ env.TMP_BUILD_DIR }}
@@ -179,91 +179,91 @@ jobs:
           # Upload tar balls to s3 so that we don't have to rebuild if they have already built
           aws s3 cp ./tmp/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz s3://sui-releases/releases/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz || true
 
-      - name: Publish Windows sui binary to Chocolatey
-        if: ${{ matrix.os == 'windows-ghcloud' && contains(env.sui_tag, 'testnet') }}
-        shell: bash
-        run: |
-          choco install checksum
-          export sui_sha=$(checksum -t sha256 ${{ env.TMP_BUILD_DIR }}/sui.exe)
-          cd chocolatey
+  #     - name: Publish Windows sui binary to Chocolatey
+  #       if: ${{ matrix.os == 'windows-ghcloud' && contains(env.sui_tag, 'testnet') }}
+  #       shell: bash
+  #       run: |
+  #         choco install checksum
+  #         export sui_sha=$(checksum -t sha256 ${{ env.TMP_BUILD_DIR }}/sui.exe)
+  #         cd chocolatey
 
-          cat <<EOF >>VERIFICATION.txt
-          Sui Binary verification steps
-          1. Download https://github.com/MystenLabs/sui/releases/download/${{ env.sui_tag }}/sui-${{ env.sui_tag }}-windows-x86_64.tgz
-          2. Extract sui.exe
-          3. Verify binary: checksum.exe -t sha256 sui.exe: ${sui_sha}
+  #         cat <<EOF >>VERIFICATION.txt
+  #         Sui Binary verification steps
+  #         1. Download https://github.com/MystenLabs/sui/releases/download/${{ env.sui_tag }}/sui-${{ env.sui_tag }}-windows-x86_64.tgz
+  #         2. Extract sui.exe
+  #         3. Verify binary: checksum.exe -t sha256 sui.exe: ${sui_sha}
 
-          File 'LICENSE.txt' is obtained from: https://github.com/MystenLabs/sui/blob/main/LICENSE
-          EOF
+  #         File 'LICENSE.txt' is obtained from: https://github.com/MystenLabs/sui/blob/main/LICENSE
+  #         EOF
 
-          choco pack --version ${{ env.sui_version }} configuration=release
-          choco apikey --api-key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
-          choco push sui.${{ env.sui_version }}.nupkg --source https://push.chocolatey.org/
+  #         choco pack --version ${{ env.sui_version }} configuration=release
+  #         choco apikey --api-key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
+  #         choco push sui.${{ env.sui_version }}.nupkg --source https://push.chocolatey.org/
 
-      - name: Upload release artifacts for ${{ matrix.os }} platform
-        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # pin@4.4.3
-        with:
-          name: sui-binaries-${{ matrix.os }}
-          if-no-files-found: error
-          path: |
-            ./tmp/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz
+  #     - name: Upload release artifacts for ${{ matrix.os }} platform
+  #       uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # pin@4.4.3
+  #       with:
+  #         name: sui-binaries-${{ matrix.os }}
+  #         if-no-files-found: error
+  #         path: |
+  #           ./tmp/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz
 
-      - name: Attach artifacts to ${{ env.sui_tag }} release in GH
-        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # pin@v1
-        with:
-          tag_name: ${{ env.sui_tag }}
-          files: |
-            ./tmp/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz
+  #     - name: Attach artifacts to ${{ env.sui_tag }} release in GH
+  #       uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # pin@v1
+  #       with:
+  #         tag_name: ${{ env.sui_tag }}
+  #         files: |
+  #           ./tmp/sui-${{ env.sui_tag }}-${{ env.os_type }}.tgz
 
-  update-homebrew-formula:
-    name: Run brew bump-formula-pr for sui on testnet releases
-    needs: release-build
-    runs-on: ubuntu-latest
-    # releasing sui cli on testnet releases because it lags `main` less than mainnet, but is more likely to be stable than devnet
-    if: ${{ contains( inputs.sui_tag, 'testnet') || contains( github.ref, 'testnet') }}
-    steps:
-      - name: Clean up tag name ${{ env.TAG_NAME }}
-        shell: bash
-        run: |
-          echo "sui_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
-          echo "versionless_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'// | sed s/'testnet\-v'//)" >> $GITHUB_ENV
-      - uses: mislav/bump-homebrew-formula-action@b3327118b2153c82da63fd9cbf58942146ee99f0 # pin@v3
-        with:
-          formula-name: sui
-          create-pullrequest: true
-          tag-name: "${{ env.sui_tag }}"
-          commit-message: |
-            {{formulaName}} ${{ env.versionless_tag }}
+  # update-homebrew-formula:
+  #   name: Run brew bump-formula-pr for sui on testnet releases
+  #   needs: release-build
+  #   runs-on: ubuntu-latest
+  #   # releasing sui cli on testnet releases because it lags `main` less than mainnet, but is more likely to be stable than devnet
+  #   if: ${{ contains( inputs.sui_tag, 'testnet') || contains( github.ref, 'testnet') }}
+  #   steps:
+  #     - name: Clean up tag name ${{ env.TAG_NAME }}
+  #       shell: bash
+  #       run: |
+  #         echo "sui_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'//)" >> $GITHUB_ENV
+  #         echo "versionless_tag=$(echo ${{ env.TAG_NAME }} | sed s/'refs\/tags\/'// | sed s/'testnet\-v'//)" >> $GITHUB_ENV
+  #     - uses: mislav/bump-homebrew-formula-action@b3327118b2153c82da63fd9cbf58942146ee99f0 # pin@v3
+  #       with:
+  #         formula-name: sui
+  #         create-pullrequest: true
+  #         tag-name: "${{ env.sui_tag }}"
+  #         commit-message: |
+  #           {{formulaName}} ${{ env.versionless_tag }}
 
-            Created by https://github.com/mislav/bump-homebrew-formula-action
+  #           Created by https://github.com/mislav/bump-homebrew-formula-action
 
-            From release: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        env:
-          # https://github.com/settings/tokens/new?scopes=public_repo,workflow
-          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_GH_FORMULA_BUMP }}
+  #           From release: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #       env:
+  #         # https://github.com/settings/tokens/new?scopes=public_repo,workflow
+  #         COMMITTER_TOKEN: ${{ secrets.HOMEBREW_GH_FORMULA_BUMP }}
 
-  # Tag all sui images with release tag, so that they can be easily found
-  tag-docker-hub-images:
-    name: Tag sui docker images in DockerHub
-    runs-on: ubuntu-latest
-    steps:
-      - name: Dispatch Tagging of images in DockerHub, in MystenLabs/sui-operations
-        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # pin@v3.0.0
-        with:
-          repository: MystenLabs/sui-operations
-          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
-          event-type: tag-docker-images
-          client-payload: '{"sui_commit": "${{ github.sha }}", "repo_name": "all", "tag": "${{ env.TAG_NAME }}"}'
+  # # Tag all sui images with release tag, so that they can be easily found
+  # tag-docker-hub-images:
+  #   name: Tag sui docker images in DockerHub
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Dispatch Tagging of images in DockerHub, in MystenLabs/sui-operations
+  #       uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # pin@v3.0.0
+  #       with:
+  #         repository: MystenLabs/sui-operations
+  #         token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
+  #         event-type: tag-docker-images
+  #         client-payload: '{"sui_commit": "${{ github.sha }}", "repo_name": "all", "tag": "${{ env.TAG_NAME }}"}'
 
-  # Tag all sui images with release tag, so that they can be easily found
-  tag-release-binaries-in-s3:
-    name: Tag sui binaries in s3
-    runs-on: ubuntu-latest
-    steps:
-      - name: Dispatch Release binaries builds in MystenLabs/sui-operations
-        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # pin@v3.0.0
-        with:
-          repository: MystenLabs/sui-operations
-          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
-          event-type: build-release-binaries
-          client-payload: '{"sui_commit": "${{ github.sha }}", "tag_name": "${{ env.TAG_NAME }}"}'
+  # # Tag all sui images with release tag, so that they can be easily found
+  # tag-release-binaries-in-s3:
+  #   name: Tag sui binaries in s3
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Dispatch Release binaries builds in MystenLabs/sui-operations
+  #       uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # pin@v3.0.0
+  #       with:
+  #         repository: MystenLabs/sui-operations
+  #         token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
+  #         event-type: build-release-binaries
+  #         client-payload: '{"sui_commit": "${{ github.sha }}", "tag_name": "${{ env.TAG_NAME }}"}'
